apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-core
spec:
  selector:
    matchLabels: 
      app: management-core
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: management-core
        tier: backend
        track: stable
    spec:
      containers:
        - name: management-core
          image: neweducation/program-management-core:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 600
            timeoutSeconds: 1
          env:
            - name: CORE_DATABASE_HOST
              value: postgres-main
            - name: CORE_DATABASE_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgresUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgresPassword
---

apiVersion: v1
kind: Service
metadata:
  name: management-core
  labels:
    app: management-core
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
      app: management-core
      tier: backend
    
--- 