apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  postgresPassword: V2liYmx5V29iYmx5
  postgresRootPassword: V2liYmx5V29iYmx5
  postgresUser: U25lYWt5VXNlcg==
  postgresDatabase: bWFpbg==
type: Opaque

containers:
      - env:
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgresDatabase
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgresUser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgresPassword
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgresRootPassword
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        name: postgres-main
        volumeMounts:
          - mountPath: '/data/main-storage'
            name: postgress-main-storage
        ports:
        - containerPort: 5432
          protocol: TCP